services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # Define solo la contraseña para root
      MYSQL_DATABASE: hexagonal_cqrs # Crea automáticamente esta base de datos
    ports:
      - "3307:3306" # Usa el puerto 3307 en tu máquina
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
